### PR TITLE
[DR] Selecting a tool to manage multiple JS/TS packages in the same repository

### PR DESCRIPTION
**Pull request by jboileau99**
Included is a [DR](https://github.com/blindnet-io/blindnet.dev/blob/password-assistant/decision-records/DR-0002-password-assistant-package-manager.md) for a monorepo manager to use in the [password-assistant repository](https://github.com/blindnet-io/password-assistant). 

The related issues are blindnet-io/product-management#30 and blindnet-io/product-management#693.

After evaluating the monorepo manager options relative to our requirements and testing them while developing the password-assistant, I believe Yarn Workspaces is the best choice.

### CODE REVIEW

**Comment by jboileau99** [comment]
Moving this conversation from slack, we are discussing which monorepo manager to use for the password-assistant project.

**Comment by noelmace** [comment]
Please complete this PR description, use a more explicit title, and reference related issues.

**Comment by noelmace** [comment]
Do you (1) need my review now, or are you (2) still working on the first draft version? If (2), please remove me from the reviewer and add me again when you're done. FYI, I'd still be happy to help find a good solution, I'd just need you to gain a good enough understanding of the problem first to build the first base for discussions. In the meantime, more generic questions can be addressed using comments (just tag me whenever needed).

**Comment by jboileau99** [comment]
Hey @noelmace, I've got a better understanding of the problem and have tested various options while developing the password-assistant tool. When you have a chance, I've requested your review of the [DR](https://github.com/blindnet-io/blindnet.dev/blob/password-assistant/decision-records/DR-0002-password-assistant-package-manager.md).

**Comment by noelmace** [comment]
BTW @jboileau99, if we kept the original title, writing a DR wouldn't be justified as it's a simple choice made in the code base.

**Comment by noelmace** [comment]
Will validate the DR on Jully 7th except you have any formal objection.
@jboileau99 is expected to handle my feedback before this deadline.

**Comment by noelmace** [comment]
Postponing this decision until further notice as we don't actually need it right now, and the password assistant project is on hold.

**Comment by noelmace** [comment]
Outdated by #36.

I just squashed all commits, rebased the branch, and fix the same small presentation issues. I'll then update the DR to make it a final DR proposal.

**Pull request closed without merging**
